'use strict';
const BOOKS = [
  {
    id: 'b1',
    title: 'Santelmo Issue 13 — Translations',
    author: 'Various writers',
    category: 'Journal',
    year: 2025,
    price: 650,
    stock: -1,
    isbn: '29603536',
    lang: 'Filipino',
    img: 'images/Santelmo Issue 13.webp',
    issueNum: 13,
    gumroad: 'https://sananselmopress.gumroad.com/l/Sant13',
    blurb:
      'Natatanging isyu sa pagsalin sa Filipino; tampok ang 50 sa mga batikang manunulat ng ating bansa. Ang isyu ng Santelmo na ito ay itinuturing na komprehensibong sangguni tungkol sa pagsasalin.',
  },
  {
    id: 'b2',
    title: 'Hanggahan at Pagtula',
    editor: 'RR Cagalingan, Karl Orit, Romulo Baquiran Jr.',
    category: 'Poetry',
    year: 2025,
    price: 350,
    stock: -1,
    isbn: '9786218230439',
    lang: 'English & Filipino',
    img: 'images/Hanggahan at Pagtula.webp',
    blurb:
      "A compilation of the winning poems of San Anselmo Publications, Inc.'s annual national poetry challenge in 2024",
  },
  {
    id: 'b3',
    title: 'Herstory',
    author: 'Various authors',
    category: 'Non-Fiction',
    year: 2025,
    price: 750,
    stock: -1,
    isbn: '',
    lang: 'English',
    img: 'images/Herstory.webp',
    gumroad: 'https://sananselmopress.gumroad.com/l/herstory',
    blurb:
      '20+ inspiring women —public servants, activists, advocates, artists— write about their reflections on Martial Law, the 1986 EDSA People Power Revolution, and working in government.',
  },
  {
    id: 'b4',
    title: 'Walang Makitang Langit',
    author: 'Che Sarigumba',
    category: 'Fiction',
    year: 2025,
    price: 450,
    stock: -1,
    isbn: '9786218230415',
    lang: 'Filipino',
    img: 'images/Walang Makitang Langit.webp',
    blurb:
      'Sundan ang peryodistang si Patring sa kanyang pakikibaka sa korapsyon, patayan, krimen at pag-ibig sa gitna ng drug war.',
  },
  {
    id: 'b5',
    title: 'Dog Country',
    author: 'Marvin B. Aceron',
    category: 'Poetry',
    year: 2025,
    price: 200,
    stock: -1,
    isbn: '9786218230392',
    lang: 'English',
    img: 'images/Dog Country.webp',
    gumroad: 'https://sananselmopress.gumroad.com/l/Dog',
    blurb:
      'A book of poems where dogs speak. They remember wars. Toast lost loves. Debate the use of power. Sing jazz. Tell the truths humans refuse to say. At the center: "Dogressman," a one-act verse play. A secret assembly of animals. A vote: should we take back the gift of speech from humankind? And then there\'s "The Dogs of Jabalya," a poem that stares straight into the dark. You will not walk away unchanged. This is not just a book. It is a silence returned. A howl made clean.',
  },
  {
    id: 'b6',
    title: 'Reinventing Resistance (Memoir of an Accidental Activist)',
    author: 'Ed Garcia',
    category: 'Non-Fiction',
    year: 2025,
    price: 750,
    stock: -1,
    isbn: '9786218230378',
    lang: 'English',
    img: 'images/Reinventing Resistance.webp',
    gumroad: 'https://sananselmopress.gumroad.com/l/iykmak',
    blurb:
      '"A Memoir which records our country\'s struggle against the dictatorship. Reminds me of a friend forged in the streets and the stand-off at the Welcome Rotunda, braving tear gas and water cannons at the height of martial law. Courage, commitment and consistency—hallmarks of a unique Memoir that is a must reading for our youth." — former senator Bobby Tañada',
  },
  {
    id: 'b44',
    title: 'Chronicle of a Life Untold: A Testament to Hope',
    author: 'Ed Garcia',
    category: 'Non-Fiction',
    year: 2026,
    price: 350,
    stock: -1,
    isbn: '',
    lang: 'English',
    img: 'images/Chronicles of a Life Untold .webp',
    blurb:
      'In this retelling of his life story, Ed Garcia provides a stirring call to action for a new generation. The book reflects on a past where people remained undeterred by repressive rule and corrupt leadership, instead choosing to pursue a path of just peace. As we face modern challenges of systemic corruption, this work serves as a reminder that we are "bearers of hope which cannot be extinguished and will not die".',
  },
  {
    id: 'b7',
    title: 'Santelmo Issue 12 — Crossroads',
    author: 'Various writers',
    category: 'Journal',
    year: 2025,
    price: 650,
    stock: -1,
    isbn: '29603536',
    lang: 'English & Filipino',
    img: 'images/Santelmo Issue 12.webp',
    issueNum: 12,
    gumroad: 'https://sananselmopress.gumroad.com/l/dnxpa',
    blurb:
      'An incendiary collection of essays, poems, fiction, and political art from some of the country\'s fiercest voices.\n\nSpecial Feature: Spotlight on Heidi Lloce-Mendoza, former COA Commissioner and long-time public servant, in "Audit is Life!" by Adelle Chua—a gripping portrait of integrity under fire.\n\nAlso inside: Poems by Marvin B. Aceron, Jim Pascual Agustin, and Alma Anonas-Carpio; a bold art feature on political cartoons; a special visual folio by Lourd de Veyra; and sharp political and literary essays from Ian Rosales Casocot, Alfred A. Yuson, and Gay Ace Domingo.',
  },
  {
    id: 'b8',
    title: 'Santelmo Issue 11 — Pelikula Journal',
    author: 'Various writers',
    category: 'Journal',
    year: 2024,
    price: 650,
    stock: -1,
    isbn: '29603536',
    lang: 'English & Filipino',
    img: 'images/Santelmo issue 11.webp',
    issueNum: 11,
    note: 'Printed on Demand',
    gumroad: 'https://sananselmopress.gumroad.com/l/Pelikula',
    blurb:
      "Santelmo Magazine Issue Number 11 — Pelikula Journal is Santelmo's thickest issue yet at 232 pages. Guest-edited by Noel Ferrer, the magnificent volume gathers both the established and new voices of Philippine cinema such as directors Jim Libiran, Jose Javier Reyes, Paolo Villaluna, and Pepe Diokno, writers Ricky Lee, Giancarlo Abrahan, Sarge Lacuesta, Jerry Gracio, and Alfred Yuson, animator Avid Liongoren, producer Nessa Valdellon, critics Patrick Flores and Joel David, and many others. Includes tributes to Mother Lily Monteverde, Marilou Diaz-Abaya, Jaclyn Jose, Peque Gallaga, and features on Nora Aunor and Vilma Santos.",
  },
  {
    id: 'b9',
    title: 'Santelmo Issue 10 — Kabataan Isyu',
    author: 'Various writers',
    category: 'Journal',
    year: 2024,
    price: 650,
    stock: -1,
    isbn: '29603536',
    lang: 'English & Filipino',
    img: 'images/Santelmo Issue 10.webp',
    issueNum: 10,
    blurb:
      "The theme of Santelmo Magazine Issue 10 is youth. Established and new writers look back on the lessons they've learned, realizing that every decision, calculated risk and encounter was an opportunity to live authentically. Contents include works by National Artist Virgilio Almario, Jose Victor Torres, Frank Cimatu, and more.",
  },
  {
    id: 'b10',
    title: 'Ano ang Demokrasya?',
    author: 'Virgilio S. Almario',
    category: "Children's Literature",
    year: 2024,
    price: 300,
    stock: -1,
    isbn: '9786218230347',
    lang: 'Filipino',
    img: 'images/Ano ang Demokrasya.webp',
    blurb:
      'Bibigyan ng masinsinang paliwanag ng Pambansang Alagad ng Sining na si Virgilio S. Almario kung ano nga ba talaga ang demokrasya, mula sa pinagmulan nito sa sinauang Griyego hanggang sa pag-usbong nito sa kasaysayan ng Pilipinas.',
  },
  {
    id: 'b11',
    title: 'Sa Bingit ng mga Panaginip',
    author: 'Various Authors',
    category: 'Poetry',
    year: 2024,
    price: 350,
    stock: -1,
    isbn: '9786218230330',
    lang: 'Filipino',
    img: 'images/Sa Bingit ng Panaginip.webp',
    blurb:
      'Antolohiya ng mga nagwaging tula mula sa Pambansang Araw ng Pagtula 2023. Tampok dito ang pinakamahusay na akda ng mga makatang Pilipino na sumagot sa mga hamon ng pagninilay sa sarili, kalusugan ng bayan, katarungan, kalayaan at kapangyarihan ng salita.',
  },
  {
    id: 'b12',
    title: 'Tagay!',
    editor: 'Mike Doria',
    category: 'Poetry',
    year: 2025,
    price: 165,
    stock: -1,
    isbn: '9786218230354',
    lang: 'English & Filipino',
    img: 'images/Tagay!.webp',
    blurb:
      "From San Anselmo Press' Pamphlet series comes a collection of poems and essays in Filipino and English that celebrate life's milestones and journeys. The authors include Mike Doria, Christine Marie Lim Magpile, Tag Cavello, Richard Muñiz, Nathaniel Dela Cruz, Mara Carr Umpad, Josephine Rustomji, Rossana Unson, Alexis Araneta, Lourd Gregory Crisol, Jizelle Naval, Voltaire Bacsa, and Marvin Aceron.",
  },
  {
    id: 'b13',
    title: "Surviving 'til First Light",
    editor: 'Dulce Sanchez',
    category: 'Anthology',
    year: 2024,
    price: 165,
    stock: -1,
    isbn: '9786218230323',
    lang: 'English',
    img: 'images/Surviving _til First Light.webp',
    blurb:
      "From San Anselmo Press' Pamphlet series comes a collection of poems, fiction and non-fiction that illustrates the complexities of recovery and living once more. Writers: Mookie Katigbak-Lacuesta, Mavi Arcega, Martin Macasaet, Tag Cavello, Merlin Alunan, Jan Philippe V. Carpio, Alvin Rosales, David Montecillo, Macario Ofilada Mina, Rossana L. Unson, Bill Fuentes and Alma Anonas-Carpio.",
  },
  {
    id: 'b14',
    title: 'Rebirth',
    editor: 'Mike Doria',
    category: 'Anthology',
    year: 2024,
    price: 165,
    stock: -2,
    isbn: '9786218230316',
    lang: 'English',
    img: 'images/Rebirth.webp',
    note: 'Currently Not Available',
    blurb:
      'Another title from San Anselmo Press\' Pamphlet Series, "Rebirth" captures the recollections of loss, grief, and separation during the happiest time of the year. The anthology gracefully celebrates the recovery of the souls who despaired behind the bright Christmas lights and beneath the fireworks.',
  },
  {
    id: 'b15',
    title: 'Santelmo Issue 9 — Genius Loci',
    author: 'Various writers',
    category: 'Journal',
    year: 2024,
    price: 650,
    stock: -1,
    isbn: '29603536',
    lang: 'English & Filipino',
    img: 'images/Santelmo Issue 9.webp',
    issueNum: 9,
    blurb:
      "Wander through the wonder of words through the essays, articles, short stories and poems in Santelmo Issue 9. A sampling of the contents: Bing Caballero takes us to Finland. Solana Perez writes about her journey to Russia. Danton Remoto's poems traverse Boracay, Zambales, Angkor Wat and Oxford.",
  },
  {
    id: 'b16',
    title: 'Six Filipino Women for Justice',
    editor: 'Asuncion David Maramba',
    category: 'Non-Fiction',
    year: 2024,
    price: 720,
    stock: 0,
    isbn: '9786218230293',
    lang: 'English',
    img: 'images/Six Filipino Women for Justice.webp',
    note: 'Sold Out, Awaiting 2nd Printing',
    gumroad: 'https://sananselmopress.gumroad.com/l/Risa',
    blurb:
      '"Six Filipino Women for Justice" is a profound exploration of resilience and the quest for equity. Editor Asuncion David Maramba crafts an insightful anthology that casts light on six Filipino women at the forefront of challenging and navigating through the nation\'s flawed judicial landscape.',
  },
  {
    id: 'b17',
    title: 'Lubog sa Ulap',
    author: 'Emmanuel Quintos Velasco',
    category: 'Poetry',
    year: 2024,
    price: 350,
    stock: -1,
    isbn: '9786218230309',
    lang: 'Filipino',
    img: 'images/Lubog Sa Ulap.webp',
    blurb:
      'Bagong aklat ng mga tula mula sa 2018 National Book Award winner na si Emmanuel Quintos Velasco. Inilarawan ng Pambansang Alagad ng Sining na si Ginoong Virgilio Almario na ang mga tula ni Emman ay isang pag-uusisa sa kasalukuyan laban sa lente ng nakamihasnan.',
  },
  {
    id: 'b18',
    title: 'Santelmo Issue 8 — Food & Culinary Culture',
    author: 'Various writers',
    category: 'Journal',
    year: 2024,
    price: 650,
    stock: -1,
    isbn: '29603536',
    lang: 'English & Filipino',
    img: 'images/Santelmo Issue 8.webp',
    issueNum: 8,
    blurb:
      'The eighth issue of Santelmo Literary Magazine delves into the culinary arts as not just a field of creativity and skill but as a medium through which people experience, remember and convey love.',
  },
  {
    id: 'b19',
    title: 'Santelmo Issue 7 — Health & Wellness',
    author: 'Various writers',
    category: 'Journal',
    year: 2024,
    price: 650,
    stock: -1,
    isbn: '29603536',
    lang: 'English & Filipino',
    img: 'images/Santelmo Issue 7.webp',
    issueNum: 7,
    gumroad: 'https://sananselmopress.gumroad.com/l/S7',
    blurb:
      'The seventh issue of Santelmo Literary Magazine is a tribute to literature as a guiding light amid the chaos and challenges of modern living. In the words of Executive Publisher Marvin Aceron, "(The issue) is a celebration of how words can heal, connect, and empower."',
  },
  {
    id: 'b20',
    title: 'Specimen Zero',
    author: 'Joel Pablo Salud',
    category: 'Fiction',
    year: 2023,
    price: 550,
    stock: -1,
    isbn: '978621230262',
    lang: 'English',
    img: 'images/Specimen Zero.webp',
    blurb:
      '"Anime, computer games, social media and popular culture comingle in this fantastic novel. An intellectual novel, it ranges widely from Greek and Mesopotamian myths to the threat of a nuclear doomsday." —Danton Remoto',
  },
  {
    id: 'b21',
    title: 'Memory & Freedom',
    editor: 'Alma Anonas-Carpio',
    category: 'Anthology',
    year: 2023,
    price: 200,
    stock: -1,
    isbn: '9786218230279',
    lang: 'English',
    img: 'images/Memory and Freedom.webp',
    blurb:
      "Contained in San Anselmo Press' first chapbook are short but powerful reads: fiction, poetry, prose vignettes taken from life itself. These little stories, small poems and beloved memories give us identity, purpose, drive and the strength to face each day with courage.",
  },
  {
    id: 'b22',
    title: 'Kafka in the Tropics',
    author: 'Krip Yuson',
    category: 'Poetry',
    year: 2023,
    price: 250,
    stock: 0,
    isbn: '9786218230255',
    lang: 'English',
    img: 'images/Kafka in the Topics.webp',
    note: 'Sold Out, Awaiting 2nd Printing',
    blurb:
      'Noted author Alfred "Krip" Yuson weaves his literary magic again with his enchanting and thought-provoking poetry that brings the reader into an uplifting, wonderful journey!',
  },
  {
    id: 'b23',
    title: 'Conversations With Mommy',
    author: 'Rene C. de Jesus',
    category: 'Inspirational',
    year: 2024,
    price: 350,
    stock: -1,
    isbn: '9786218230231',
    lang: 'English',
    img: 'images/Conversations with Mommy.webp',
    blurb:
      'In this inspiring bestseller, corporate executive Rene C. de Jesus s in a series of letters his love for his mother who was facing imminent death.',
  },
  {
    id: 'b24',
    title: 'Radical: Readings in Rizal & History',
    author: 'John Nery',
    category: 'Non-Fiction',
    year: 2023,
    price: 550,
    stock: -1,
    isbn: '9786218230248',
    lang: 'English',
    img: 'images/Radical.webp',
    blurb:
      'Veteran journalist John Nery has channeled his avid passion on Jose Rizal into this volume of essays. Reviewers describe the compelling book as "great" and "scholarly". This is definitely a must-read for history buffs, patriots, teachers and the youth.',
  },
  {
    id: 'b25',
    title: 'Santelmo Issue 6',
    author: 'Various writers',
    category: 'Journal',
    year: 2023,
    price: 650,
    stock: -1,
    isbn: '29603536',
    lang: 'English & Filipino',
    img: 'images/Santelmo Issue 6.webp',
    issueNum: 6,
    gumroad: 'https://sananselmopress.gumroad.com/l/cmfpg',
    blurb:
      'Santelmo Issue Number 6 is a literary treasure chest, showcasing the brilliant works of major Filipino poets, writers and artists, including two National Artists for Literature. The issue has a special focus on the poets and artists who created works for the "Kislap Diwa" exhibit at the National Museum.',
  },
  {
    id: 'b26',
    title: 'Santelmo Issue 5 — The Justice Issue',
    author: 'Various writers',
    category: 'Journal',
    year: 2023,
    price: 650,
    stock: -1,
    isbn: '29603536',
    lang: 'English & Filipino',
    img: 'images/Santelmo Issue 5.webp',
    issueNum: 5,
    gumroad: 'https://sananselmopress.gumroad.com/l/nbmqmb',
    blurb:
      'This issue is devoted to the theme of Justice with certain works inspired by former Senator Atty. Leila de Lima, who, at that time, was still in prison amid court acquittal for two of three criminal charges.',
  },
  {
    id: 'b27',
    title: 'Confessions of An Ex-Jesuit',
    author: 'Ibarra M. Gonzalez, PhD',
    category: 'Inspirational',
    year: 2019,
    price: 700,
    stock: -1,
    isbn: '9786219602174',
    lang: 'English',
    img: 'images/Confessions of an Ex-Jesuit.webp',
    blurb:
      'In Confessions of an Ex-Jesuit, Ibarra M. Gonzalez, PhD, reflects upon his decision and life after leaving the Society of Jesus and reiterates the Gospel truth that we are all consecrated priests through Baptism.',
  },
  {
    id: 'b28',
    title:
      'A Quick Guide: Top 20 Changes to the Rules of Civil Procedure & Revised Rules on Evidence',
    author: 'Noel Oliver Punzalan, JD',
    category: 'General Reference',
    year: 2020,
    price: 249,
    stock: -1,
    isbn: '9786219602198',
    lang: 'English',
    img: 'images/Top 20 Changes.webp',
    blurb:
      'Far Eastern University law professor Atty. Noel Oliver Punzalan (+) has compiled the most pertinent changes in the rules of court that was implemented in May 2020. A handy guide for lawyers and law students. Certified bestseller with almost 3,000 copies sold in less than eight months!',
  },
  {
    id: 'b29',
    title: 'Rules for the E-Notary',
    author: 'Shyanne T. Juan-Monera, JD',
    category: 'General Reference',
    year: 2020,
    price: 249,
    stock: -1,
    isbn: '978621',
    lang: 'English',
    img: 'images/Rules For The E-notary.webp',
    blurb:
      'What law practitioners need to know about the Rules for the E-Notary at a quick glance. A must-have for those in the notarial practice.',
  },
  {
    id: 'b30',
    title: 'Seachange! Successor Generation',
    author: 'Ed Garcia',
    category: 'Inspirational',
    year: 2020,
    price: 350,
    stock: -1,
    isbn: '',
    lang: 'English',
    img: 'images/Seachange!.webp',
    blurb:
      'Prof. Ed Garcia reflects on electoral campaigns, social movements, and passing the baton to the next generation. A collection of essays written during a critical period in Philippine democracy.',
  },
  {
    id: 'b31',
    title: 'Defiant Hope!',
    author: 'Ed Garcia',
    category: 'Inspirational',
    year: 2020,
    price: 350,
    stock: -1,
    isbn: '',
    lang: 'English',
    img: 'images/Defiant Hope!!.webp',
    blurb:
      'Prof. Ed Garcia, distinguished university professor and one of the framers of the 1987 Constitution, began writing these essays during the height of the pandemic lockdown in 2020.',
  },
  {
    id: 'b32',
    title: 'Companions! XJ Narratives',
    author: 'Gemino H. Abad, L.F. Habito, Ed Garcia',
    category: 'Inspirational',
    year: 2021,
    price: 800,
    stock: -1,
    isbn: '9786218230057',
    lang: 'English',
    img: 'images/Companions! XJ Narratives.webp',
    blurb:
      'The 400+ page book of essays presents the lives of former priests and seminarians of the Society of Jesus. In 2023, the book won the Gintong Aklat Award — Spiritual category.',
  },
  {
    id: 'b33',
    title: 'In The Line of Fire Lectures',
    author: 'Joel Pablo Salud',
    category: 'Non-Fiction',
    year: 2021,
    price: 350,
    stock: -1,
    isbn: '9786218230118',
    lang: 'English',
    img: 'images/In the Line of Fire.webp',
    blurb:
      'The book is a collection of talks and lectures on journalism delivered in schools all over the country. It is envisioned as a guide for current and future journalists in the age of fake news.',
  },
  {
    id: 'b34',
    title: 'Servant Leader Leni Robredo',
    author: 'Ed Garcia',
    category: 'Biography',
    year: 2022,
    price: 570,
    stock: 0,
    isbn: '',
    lang: 'English',
    img: 'images/Servant Leader Leni Robredo.webp',
    note: 'Sold Out',
    blurb:
      'This is the biography of former Vice-President Leni Robredo as written by Constitutional framer Prof. Ed Garcia. Features articles written by Bam Aquino, Dean Mel Sta. Maria, Philip Dy, Aika Robredo; poems by Fr. Albert Alejo, SJ, Jim Pascual Agustin, Gemino H. Abad, and more.',
  },
  {
    id: 'b35',
    title: 'Mga Poon, Mga Piyon, Mga Pusong, Isang Pusong',
    author: 'Virgilio S. Almario',
    category: 'Poetry',
    year: 2022,
    price: 350,
    stock: -1,
    isbn: '9786218230194',
    lang: 'Filipino',
    img: 'images/Mga Poon, mga Piyon, Mga Pusong, Isang Pusong.webp',
    blurb:
      'Koleksiyon ng mga bagong tula ng Pambansang Alagad ng Sining na si Virgilio Almario (a.k.a. Rio Alma) na isinulat niya bunga rin ng kanyang pakikilahok at pangangampanya sa hanay ng mga Kakampink.',
  },
  {
    id: 'b36',
    title: 'The Mountain That Grew',
    author: 'Krip Yuson',
    category: "Children's Literature",
    year: 2022,
    price: 750,
    stock: -1,
    isbn: '9786218230187',
    lang: 'English',
    img: 'images/The Mountain That Grew.webp',
    blurb:
      'Celebrated author Alfred "Krip" Yuson writes about a mountain that keeps growing and the people who attempt to scale it to discover what is behind the mystery. A timeless tale for both children and adults.',
  },
  {
    id: 'b37',
    title: 'Bloodred Dragonflies',
    author: 'Jim Pascual Agustin',
    category: 'Poetry',
    year: 2022,
    price: 450,
    stock: -1,
    isbn: '9781928476467',
    lang: 'English & Filipino',
    img: 'images/Bloodred Dragonflies.webp',
    blurb:
      "This is Jim Pascual Agustin's first published work in South Africa. The volume contains a selection from three decades of work, including new poems and some recently translated versions of poems from the Filipino.",
  },
  {
    id: 'b38',
    title: 'Artfully Speaking & Other Essays',
    author: 'Jerry R. Yapo',
    category: 'Non-Fiction',
    year: 2022,
    price: 350,
    stock: -1,
    isbn: '9786218230200',
    lang: 'English',
    img: 'images/Artfully Speaking.webp',
    blurb:
      'A collection of essays by University of the Philippines Los Baños Associate Professor Jerry R. Yapo revealing his reflections on personal experiences, as well as his take on the subject of art. The book features art works by six Filipino artists.',
  },
  {
    id: 'b39',
    title: 'Jose Corazon de Jesus: Mga Piling Tula',
    editor: 'Virgilio S. Almario',
    category: 'Poetry',
    year: 2022,
    price: 550,
    stock: -1,
    isbn: '9786218230224',
    lang: 'Filipino',
    img: 'images/Mga Piling Tula.webp',
    blurb:
      'Para sa ika-128 ng kaarawan ng "pambansang makata ng bayan sa ika-20 na siglo," naglabas ang Pambansang Alagad ng Sining na si Virgilio S. Almario ng ikalawang edisyon ng aklat na "Jose Corazon de Jesus: Mga Piling Tula." Laman ay higit pa sa 231 na pahina ng mga tula ni Huseng Batute.',
  },
  {
    id: 'b40',
    title: 'Santelmo Issue 1',
    author: 'Various writers',
    category: 'Journal',
    year: 2022,
    price: 650,
    stock: -1,
    isbn: '29603536',
    lang: 'English & Filipino',
    img: 'images/Santelmo Issue 1.webp',
    issueNum: 1,
    gumroad: 'https://sananselmopress.gumroad.com/l/hlkie',
    blurb:
      'National Artists Virgilio Almario and Gemino Abad are among the 63 writers whose works are featured in the first issue of Santelmo: Liwanag sa Dilim, released on June 30, 2022. Theme: "Faith, Hope and Rebirth."',
  },
  {
    id: 'b41',
    title: 'Santelmo Issue 2',
    author: 'Various writers',
    category: 'Journal',
    year: 2022,
    price: 650,
    stock: 0,
    isbn: '29603536',
    lang: 'English & Filipino',
    img: 'images/Santelmo Issue 2.webp',
    issueNum: 2,
    note: 'Sold Out',
    gumroad: 'https://sananselmopress.gumroad.com/l/S2',
    blurb:
      'Santelmo Issue Number 2 builds on the theme of hope. It features a painting by National Artist for Music Ryan Cayabyab on the cover, and opens with a section devoted to literary translation.',
  },
  {
    id: 'b42',
    title: 'Santelmo Issue 3',
    author: 'Various writers',
    category: 'Journal',
    year: 2022,
    price: 650,
    stock: -1,
    isbn: '29603536',
    lang: 'English & Filipino',
    img: 'images/Santelmo Issue 3.webp',
    issueNum: 3,
    gumroad: 'https://sananselmopress.gumroad.com/l/moilr',
    blurb:
      'Santelmo Issue Number 3 contains poetry, fiction, reviews and essays in line with the theme "Future Philippines." On the cover is artwork by Celeste Lecaroz. Includes short stories by Sarge Lacuesta, Lakambini Sitoy, and Che Sarigumba; poetry by Virgilio Almario, Marne Kilates, and Joi Barrientos; an essay on Rizal in Dapitan by Howie Severino; tributes to Richard Gappi and Ericson Acosta; and works by other award-winning Filipino writers.',
  },
  {
    id: 'b43',
    title: 'Santelmo Issue 4',
    author: 'Various writers',
    category: 'Journal',
    year: 2023,
    price: 650,
    stock: -1,
    isbn: '29603536',
    lang: 'English & Filipino',
    img: 'images/Santelmo Issue 4.webp',
    issueNum: 4,
    gumroad: 'https://sananselmopress.gumroad.com/l/S4',
    blurb:
      'Building on the success of the first three issues, the fourth issue continues to showcase the poems, short stories, articles and essays of the best Filipino writers. This issue includes a tribute to the late Lualhati Bautista.',
  },
  {
    id: 'b47',
    title: 'Santelmo 14 — Cultures of EDSA',
    author: 'Various writers',
    category: 'Journal',
    year: 2026,
    price: 650,
    stock: -1,
    isbn: '',
    lang: 'English & Filipino',
    img: 'images/Santelmo Issue 14.webp',
    issueNum: 14,
    blurb: '[Blurb to follow.]',
  },
  {
    id: 'b48',
    title: 'Happy',
    author: 'Mike Doria (Ed.)',
    category: 'Poetry',
    year: 2025,
    price: 200,
    stock: -1,
    isbn: '',
    lang: 'English & Filipino',
    img: 'images/Happy.webp',
    blurb: '[Blurb to follow.]',
  },
  {
    id: 'b49',
    title: 'Farewells',
    author: 'Mike Doria (Ed.)',
    category: 'Poetry',
    year: 2025,
    price: 200,
    stock: -1,
    isbn: '',
    lang: 'English & Filipino',
    img: 'images/Farewells.webp',
    blurb: '[Blurb to follow.]',
  },
  {
    id: 'b50',
    title: 'Audit is Life: Santelmo 12 Special Feature',
    author: 'Various writers',
    category: 'Journal',
    year: 2025,
    price: 200,
    stock: -1,
    isbn: '',
    lang: 'English & Filipino',
    img: 'images/audit is life.webp',
    gumroad: 'https://sananselmopress.gumroad.com/l/wlxyig',
    blurb: 'Santelmo 12 Special Feature on auditing and accountability.',
  },
  {
    id: 'b51',
    title: 'Buhay at Banyuhay: Mga Kuwentong may Kuwenta',
    author: 'Xiao Chua',
    category: 'Non-Fiction',
    year: 2026,
    price: 600,
    stock: -1,
    isbn: '',
    lang: 'Filipino',
    img: 'images/Buhay at Banyuhay.webp',
    blurb: '[Blurb to follow.]',
  },
];

const AUTHORS = [
  {
    name: 'Virgilio S. Almario',
    bio: 'National Artist for Literature, also known as Rio Alma.',
    img: 'images/rio alma.webp',
  },
  {
    name: 'Edmundo "Ed" Garcia',
    bio: 'Constitutional framer, professor, and prolific author.',
    img: 'images/ed garcia.webp',
  },
  {
    name: 'Marvin B. Aceron',
    bio: 'Executive Publisher and author of Dog Country.',
    img: '',
  },
  {
    name: 'Joel Pablo Salud',
    bio: 'Veteran journalist, editor, and fictionist.',
    img: 'images/joel pablo salud.webp',
  },
  {
    name: 'Che Sarigumba',
    bio: 'Award-winning journalist and novelist.',
    img: 'images/che sarigumba.webp',
  },
  {
    name: 'Alfred "Krip" Yuson',
    bio: 'Noted author and poet, also known as Krip Yuson.',
    img: 'images/krip yuson.webp',
  },
  {
    name: 'Jim Pascual Agustin',
    bio: 'Acclaimed poet and translator.',
    img: 'images/jim pascual agustin.webp',
  },
  {
    name: 'John Nery',
    bio: 'Veteran journalist and history author.',
    img: 'images/john nery.webp',
  },
  {
    name: 'Asuncion David Maramba',
    bio: 'Renowned editor and literary figure.',
    img: 'images/asuncion.webp',
  },
  {
    name: 'Rene C. de Jesus',
    bio: 'Corporate executive and inspirational author.',
    img: 'images/rene.webp',
  },
  {
    name: 'Ibarra M. Gonzalez, PhD',
    bio: 'Author and former Jesuit.',
    img: 'images/ibarra.webp',
  },
  {
    name: 'Jerry R. Yapo',
    bio: 'Essayist and art critic.',
    img: 'images/jerry.webp',
  },
  {
    name: 'Emmanuel Quintos Velasco',
    bio: 'National Book Award-winning poet.',
    img: '',
  },
  { name: 'Dulce Sanchez', bio: 'Editor and poet.', img: 'images/dulce.webp' },
  {
    name: 'Mike Doria',
    bio: 'Anthology editor and writer.',
    img: 'images/mike doria.webp',
  },
  {
    name: 'Alma Anonas-Carpio',
    bio: 'Editor and literary writer.',
    img: 'images/alma.webp',
  },
  {
    name: 'Noel Oliver Punzalan, JD',
    bio: 'Law professor and legal reference author.',
    img: 'images/noel.webp',
  },
  {
    name: 'Shyanne T. Juan-Monera, JD',
    bio: 'Lawyer and legal reference author.',
    img: '',
  },
  { name: 'RR Cagalingan', bio: 'Poet and editor.', img: 'images/rr.webp' },
  {
    name: 'Xiao Chua',
    bio: 'Prominent Filipino historian, academic, and television presenter.',
    img: 'images/xiao chua.webp',
  },
  {
    name: 'Various writers',
    bio: 'Anthologies and journals featuring the finest minds in Philippine literature.',
    img: '',
  },
];

const TEAM = [
  { name: 'Celeste Lecaroz', role: 'President', img: 'images/Celeste.webp' },
  {
    name: 'Atty. Eldrige Marvin B. Aceron',
    role: 'Executive Publisher',
    img: '',
  },
  {
    name: 'Gay Ace Domingo',
    role: 'Marketing and Public Relations Head',
    img: 'images/Gay.webp',
  },
  { name: 'Marx Kristian Segundo', role: 'Book Designer', img: '' },
  { name: 'Roxan Piaje', role: 'Marketing Assistant', img: '' },
  {
    name: 'Reymond Sambrano',
    role: 'Marketing Assistant, Web Developer',
    img: '',
  },
  {
    name: 'Edzel Frince Bual',
    role: 'Marketing Assistant, Web Developer',
    img: 'images/edz 1x1.webp',
  },
];

const EVENTS = [
  {
    title: "Valentine's Donation Drive",
    date: '2026-02-14',
    type: 'Outreach',
    location: 'Quezon City Public Library',
    map: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3860.148672586482!2d121.04803847408132!3d14.64750067592869!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3397b618b3c5831f%3A0xe08fd29cb0305f63!2sQuezon%20City%20Public%20Library!5e0!3m2!1sen!2sph!4v1770736620776!5m2!1sen!2sph',
    link: 'https://www.facebook.com/sananselmopress',
  },
  {
    title: 'Philippine Book Festival 2026',
    date: '2026-03-12',
    type: 'Book Fair',
    location: 'Booth BO28 (Booktopia), Megatrade Hall, SM Megamall',
    map: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3861.2789262683973!2d121.05223857044979!3d14.58317574636838!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3397c9aed7b13797%3A0x35daf238542b2320!2sMegatrade%20Hall!5e0!3m2!1sen!2sph!4v1770736516761!5m2!1sen!2sph',
    link: 'https://www.facebook.com/sananselmopress',
  },
  {
    title: 'Chronicle of a Life Untold: A Testament to Hope',
    date: '2026-02-24',
    type: 'Book Launch',
    location: 'NGF Conference Room, De la Costa Hall, ADMU QC',
    map: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3860.2806841802553!2d121.0767891!3d14.6400019!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3397b77fa8beeb4b%3A0xf2e14d01ef111be!2sHumanities%20Building%3A%20Horacio%20de%20la%20Costa%20Hall!5e0!3m2!1sen!2sph!4v1780470668288!5m2!1sen!2sph',
    link: 'https://www.facebook.com/sananselmopress',
  },
  {
    title: 'Awit ng Debosyon',
    date: '2026-03-23',
    type: 'Outreach',
    location: 'QC Hall High Rise Building Lobby, Quezon City',
    map: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3860.1668372282575!2d121.0475173101833!3d14.646469075893966!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3397b70950b66739%3A0xa0f8a709cb1843a7!2sQuezon%20City%20Hall!5e0!3m2!1sen!2sph!4v1780470829364!5m2!1sen!2sph',
    link: 'https://www.facebook.com/sananselmopress',
  },
  {
    title: "International Women's Day Bazaar",
    date: '2026-03-24',
    type: 'Book Fair',
    location: '33rd Floor, AIA Tower, Paseo de Roxas, Makati City',
    map: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3861.729221843948!2d121.02177669999999!3d14.557471099999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3397c906767e32e7%3A0x7313fa82decaeffc!2sAIA%20Tower!5e0!3m2!1sen!2sph!4v1780470884297!5m2!1sen!2sph',
    link: 'https://www.facebook.com/sananselmopress',
  },
  {
    title: 'Día del Libro 2026',
    date: '2026-04-25',
    type: 'Book Fair',
    location: 'Booth 38, Ayala Triangle Gardens, Makati',
    map: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7723.4732089615245!2d121.0244961!3d14.557049300000003!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3397c905c953e8df%3A0xd3d03ade4df31dab!2sAyala%20Triangle%20Gardens!5e0!3m2!1sen!2sph!4v1780471134733!5m2!1sen!2sph',
    link: 'https://www.facebook.com/sananselmopress',
  },
  {
    title: 'Many Marias: Callas by Lecaroz',
    date: '2026-05-15',
    type: 'Exhibition',
    location: 'Carlos P. Romulo Auditorium Lobby, RCBC Tower, Makati',
    map: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3861.6739665778973!2d121.01364501018183!3d14.560627677996344!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3397c90961db7ab5%3A0xc5094954bbb7c0e6!2sCarlos%20P.%20Romulo%20Auditorium!5e0!3m2!1sen!2sph!4v1780471276537!5m2!1sen!2sph',
    link: 'https://www.facebook.com/sananselmopress',
  },
  {
    title: 'Santelmo 14 — Cultures of EDSA',
    date: '2026-05-23',
    type: 'Book Launch',
    location: 'Faura Hall Audio-Visual Room, ADMU QC',
    map: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3860.291663897598!2d121.07168554132993!3d14.639378039781874!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3397b77fa0102f49%3A0x534df5430b34684c!2sFaura%20AVR!5e0!3m2!1sen!2sph!4v1780471400025!5m2!1sen!2sph',
    link: 'https://www.facebook.com/sananselmopress',
  },
  {
    title: 'Manila International Book Fair 2026',
    date: '2026-09-09',
    type: 'Book Fair',
    location: 'SMX Convention Center Manila, Mall of Asia Complex, Pasay City',
    map: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7724.347641496409!2d120.98170010000001!3d14.532048!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3397c967bab80a71%3A0xcf52fb438feb5a6c!2sSMX%20Convention%20Center%20Manila!5e0!3m2!1sen!2sph!4v1780471829387!5m2!1sen!2sph',
    link: 'https://www.facebook.com/sananselmopress',
  },
];

const BOOKS_PER_SHELF = 8;
